apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
spec:
  capacity:
    storage: 10Gi  # Adjust this to match the PVC request
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /home/elight/bitwarden 
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - emi-homelab 
  persistentVolumeReclaimPolicy: Retain

