apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-cert
  namespace: plex
spec:
  secretName: plex-cert-tls
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
  commonName: plex.light-eg.xyz
  dnsNames:
  - plex.light-eg.xyz
  - '*.plex.light-eg.xyz'

