apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: plex
  name: music-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust size as needed
