kind: Service
apiVersion: v1
metadata:
  name: plex 
  namespace: plex
spec:
  type: ClusterIP 
  selector:
    app: plex
  ports:
    - protocol: TCP 
      port: 32400
      targetPort: 32400
  externalIPs:
    - 192.168.191.226

