kind: Service
apiVersion: v1
metadata:
  name: plex 
  namespace: plex
spec:
  type: LoadBalancer
  selector:
    app: plex
  ports:
    - protocol: TCP 
      port: 8080
      targetPort: 32400
  externalIPs:
    - 192.168.191.224

