apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-cert
  namespace: default 
spec:
  secretName: home-cert-tls
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
  commonName: home.light-eg.xyz
  dnsNames:
  - home.light-eg.xyz
  - '*.home.light-eg.xyz'

