apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Document Management:
        - Paperless Service:
            href: https://paper.light-eg.xyz
            description: Paperless Document Management Application

    - Entertainment:
        - Plex Service:
            href: https://plex.light-eg.xyz
            description: Plex Server

    - Password Management:
        - Vaultwarden Service:
            href: https://vaultwarden.light-eg.xyz
            description: Vaultwarden Password Management

    - Docker Container Management:
        - KASM:
            href: https://kasm.light-eg.xyz
            description: Stream Docker Containers to the Browser

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
