apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: emiljano.gjiriti12021@gmail.com 
    privateKeySecretRef:
      name: letsencrypt-dns01-private-key
    solvers:
    - dns01:
        cloudflare:
          email: emiljano.gjiriti2021@gmail.com 
          apiTokenSecretRef:
            name: cloudflare-api-key 
            key: apiKey

